import React from 'react'
import "./home.css"
import images from "../images/images"

const Home = () => {
  return (
    <div className='home_principal'>
      <section className='section_banner'>
      <h1 className='text_tittle'>HOME</h1>
      <img className='img__banner' src={images.banner} alt="" />
      </section>

      <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur veritatis nihil consequuntur, facilis voluptatem voluptatibus ea commodi eius, distinctio libero possimus, fuga veniam natus inventore ratione cupiditate? Illo, ex velit! loren*100
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis recusandae corporis ipsa dolor vitae dolorum esse aliquam explicabo eligendi cupiditate, autem laboriosam asperiores earum nostrum. Ipsum a eum quas facilis!
        Suscipit, reiciendis fuga error vitae corrupti quasi vero? Ducimus, qui! Harum fugit, aspernatur impedit reiciendis saepe voluptates unde ex quis inventore nostrum atque doloribus, nam, facere cum porro vel veniam!
        Quasi omnis nam architecto magnam veritatis repellat nihil dolor. Saepe nostrum a porro rem doloremque commodi quibusdam earum vitae obcaecati magni magnam amet totam assumenda iste, quae dicta repellat cumque.
        Labore id reprehenderit soluta aspernatur eaque, sint ullam sed molestias corrupti hic rem, voluptas cum eius consequuntur atque ex. Odit, maxime excepturi! Beatae nihil odio blanditiis maxime, quisquam alias quas.
        Numquam eius nam recusandae officia voluptatem esse quas, culpa animi quae libero distinctio sapiente debitis quod quasi cumque ut perferendis nesciunt nostrum aliquam exercitationem tempore. Dignissimos a deserunt ab tempore.
        Obcaecati officiis perferendis asperiores eum porro repellat sapiente repellendus dolorum excepturi illum? Atque fugit odit rem aperiam fugiat autem pariatur laboriosam dignissimos distinctio modi unde, nobis architecto quae facere perferendis!
        Suscipit rem deleniti provident quam natus voluptatibus laboriosam. Rerum quisquam qui totam consectetur harum numquam nulla, obcaecati nam, dolorem temporibus quas consequatur dignissimos debitis error facere porro alias. Repudiandae, debitis?
        Est quod aspernatur optio eius totam, saepe iure aperiam eos odio! Corporis beatae vero possimus natus ea quaerat hic, numquam, non, adipisci quod deleniti maiores eligendi porro! Provident, accusantium recusandae?
        Expedita et vero officiis nulla illum eum, at fugit, illo ex qui quaerat, deleniti ullam. Atque, quasi eaque magni dolores alias quod velit provident, vero aspernatur sint reprehenderit fugit est?
        Cumque sapiente facere quis, ex commodi non nemo? Amet, eligendi. Inventore id similique nulla illum, ratione incidunt nihil beatae ab, quisquam quaerat in, explicabo quod sint eum reprehenderit odit excepturi.
        Dicta voluptate quaerat voluptas amet eum dolorem deserunt esse dignissimos incidunt? Obcaecati eum voluptatum impedit voluptas officiis, similique, excepturi tenetur soluta repudiandae dolorum magni recusandae iste cupiditate in ipsa necessitatibus!
        Tempora nihil nulla officia qui voluptas deserunt. Fugit dolor nisi voluptate deleniti harum aliquam quis, ratione expedita, porro recusandae repellendus quia amet libero accusantium blanditiis sequi, nemo quod consequatur eius?
        Nostrum ducimus dolorem iure libero aspernatur, quidem vero facere ex porro saepe tempora iste repellendus fuga minima ut beatae ipsum molestias aliquid temporibus numquam, quos et sapiente error ea? Voluptates.
        Blanditiis dolore odit ut doloremque laborum exercitationem iste ab impedit, saepe libero similique harum voluptatem itaque consequuntur tempore? Amet, vero illum voluptatem aut vitae officia voluptates perferendis id eveniet distinctio!
        Voluptatem sequi animi unde rem eos beatae tempore tenetur ad natus. Veritatis, officiis minima! Temporibus omnis voluptatem perferendis, praesentium doloribus, corporis expedita enim facilis labore distinctio, cupiditate delectus sit reiciendis!
        At quia architecto magni eum tempore consectetur. Delectus qui, aspernatur soluta repellat dolore quis itaque fugit cupiditate cumque perspiciatis natus, corrupti modi? Voluptatibus, totam eius doloremque aspernatur quos repudiandae enim?
        A totam odit laborum aspernatur tenetur minus quam et dolorum eum ratione necessitatibus quasi molestias, tempora delectus voluptatem velit consequuntur? Perferendis sit aspernatur ad adipisci consequuntur, earum rem quisquam a.
        Cupiditate aliquam, ducimus illo ipsam eligendi similique aut distinctio esse dolorum, qui atque, dicta provident earum repudiandae impedit explicabo tempore quae libero fugit alias odit eos? Culpa ipsam quidem odit?
        Modi sequi, facere, ipsum natus soluta minus doloremque magni nulla, voluptates ab ex voluptas fugit porro sapiente voluptate. Numquam, facere molestiae distinctio rerum saepe sint odit consequatur deleniti tempora dolor.
        Accusamus maxime error, non quos dolores cupiditate, culpa provident delectus magnam praesentium asperiores dolore dolor cumque, optio qui at. Qui dolorum minima totam inventore aut officia, at officiis ipsum id.
        Exercitationem quaerat repellendus dolore aspernatur praesentium, fuga culpa numquam, voluptatem, sit possimus explicabo sequi commodi odit pariatur quas. Accusamus, aliquid. Molestias eligendi corrupti sunt nisi atque minima voluptatibus, ipsum aliquid!
        Magnam, reiciendis voluptates velit deserunt ad, neque quisquam repellat soluta doloremque commodi vel quam, magni dolorum aut tempora. Ratione adipisci doloremque blanditiis, itaque necessitatibus nulla animi rem hic et voluptatum!
        Dolores similique aperiam numquam! Eveniet assumenda, id ratione odio animi praesentium! Dignissimos saepe ducimus accusamus consectetur beatae enim molestias, nam nihil, ipsam facilis praesentium eum quaerat? Dolore odit porro nesciunt!
        Cupiditate veritatis officiis quibusdam ratione ipsa vitae pariatur fuga neque sit perferendis error molestiae a repellat quo adipisci itaque quia, laboriosam eius consequatur impedit odio, reprehenderit iusto? Totam, ea iste.
        Quas voluptatem, laborum debitis doloribus minima autem aspernatur omnis facilis illum optio aperiam doloremque alias blanditiis maiores quibusdam eveniet ducimus vero, fugiat cupiditate laudantium iste? Dignissimos consectetur eaque delectus cum.
        Totam libero dolorem ab optio nisi? Fugiat quibusdam explicabo voluptatum nobis obcaecati, totam atque quas molestiae quos distinctio maiores enim quam. Odit deleniti ullam odio accusamus a, tempora nobis vitae?
        Maiores ducimus quaerat voluptates quos provident explicabo incidunt dolore, quis culpa nesciunt blanditiis! Saepe maxime totam placeat adipisci pariatur in, libero voluptas cumque fuga incidunt, quo explicabo recusandae quibusdam doloremque.
        Similique dolorum esse facilis perferendis aliquam odit blanditiis aspernatur eius veritatis maxime dolores quod distinctio fugit ipsa, quas laboriosam doloribus voluptatum deleniti quam. Delectus culpa exercitationem labore, animi officia cumque?
        Suscipit aut velit fugiat, quos explicabo porro consectetur nesciunt cupiditate ducimus nobis, architecto doloremque accusantium maxime nihil laborum soluta accusamus, libero eveniet hic aliquid consequuntur totam eaque obcaecati ex. Quo?
        Culpa ipsa quibusdam optio quam, excepturi tempore saepe magni ipsum assumenda quae esse perspiciatis porro. Eius rerum repellendus fuga excepturi, eos, iusto aut placeat nemo eaque officia accusantium reprehenderit magni.
        Esse modi a accusamus numquam laudantium reprehenderit quo fuga delectus nobis facilis possimus, laboriosam, culpa quia perferendis aspernatur inventore. Corporis, veritatis! Quidem tempore minus quaerat qui voluptas accusamus molestiae nemo!
        Incidunt qui repellendus enim, possimus doloremque in nobis corrupti reiciendis quia accusantium natus eos, expedita facere quibusdam voluptatibus illo fugiat omnis sed. Ullam aperiam atque nobis doloribus quis cumque vel?
        Dolore, laborum! Amet commodi velit quasi, ad odit nesciunt id quam deserunt nemo natus repellendus sit laboriosam cupiditate ullam dolorem magnam distinctio! Velit delectus adipisci quaerat nihil iusto, debitis ullam?
        Natus hic harum molestias architecto quae, sunt recusandae vero. Voluptas, sapiente quos ullam libero quae blanditiis assumenda, ab vel ratione, dolorum corporis architecto harum tempore! Eos, minus! Cupiditate, laudantium voluptas.
        Dolores porro nulla quaerat veniam impedit quasi iure repudiandae voluptatem earum optio perspiciatis illo, maxime consequatur eligendi dignissimos eos cum totam ad dolorum debitis aut? Ipsam quod harum aliquam labore!
        Quibusdam unde eaque atque laboriosam error nobis sed maxime? Eveniet, ducimus modi placeat nulla quia aspernatur dicta perspiciatis blanditiis reiciendis optio minus molestiae hic aperiam ipsum culpa quasi ex nesciunt.
        Facilis iusto dignissimos voluptas consectetur soluta dolore deleniti dolorem quo fugit architecto non ut tempore aliquam, provident vel modi aut quae consequatur impedit labore hic quisquam. Nostrum ratione quis neque.
        Provident labore distinctio veniam assumenda placeat nam pariatur delectus et beatae! Ipsam esse dolorem temporibus illo nobis ducimus beatae nihil possimus asperiores. Ut, ducimus rerum fugiat illo quod possimus repellendus.
        Placeat nihil dolores ipsa provident voluptate, iusto odit. Vitae molestias quis numquam ratione delectus ea quo similique. Modi, est nam a quasi sit, quibusdam tenetur eius quae consequatur, laboriosam rem!
        Inventore exercitationem nisi temporibus reprehenderit aut, odio optio incidunt praesentium repellendus molestiae, nam corporis officiis dolore voluptatem. Numquam alias fugiat perferendis ipsam dolore sapiente porro veniam quasi eius assumenda. Vitae.
        At dolores recusandae possimus. Ut ipsum laborum excepturi rem eius fugit, distinctio voluptatibus molestiae aperiam nostrum hic deserunt ducimus adipisci doloribus accusantium magnam iste ullam deleniti asperiores ipsam, nesciunt dolorem.
        Id sit dicta quidem architecto perspiciatis possimus porro aliquid neque, aliquam illum illo nostrum sunt assumenda odio eos eveniet voluptates nam minus nihil repellendus, vitae est fugit? Repellendus, praesentium nam.
        Animi quisquam perspiciatis rem quo? Itaque tempora totam nam, maxime, ex repellendus iure saepe rerum odio nesciunt exercitationem molestias odit minus optio dignissimos sint in quia molestiae quam fugiat impedit.
        Labore ullam deserunt magni aliquam provident esse. Iusto, soluta minus? Quidem, exercitationem doloribus? Recusandae expedita debitis obcaecati fuga, at ratione voluptatibus perferendis ab incidunt placeat officia doloribus dolorem labore vero!
        Commodi qui, doloremque aliquid sed harum eligendi maiores voluptatibus eum totam corrupti magni vel ex? Sunt qui vel minima facilis exercitationem a soluta molestias dolorum saepe iusto reiciendis, nostrum unde.
        Mollitia tempora illum, voluptas fugit porro sapiente corrupti itaque non blanditiis repellendus quo dolore dolor hic eius totam veritatis! Assumenda sapiente ea, aliquid dolor voluptatem reiciendis dicta earum consequatur voluptas?
        Dolor magnam, animi reprehenderit impedit eos vero. Labore asperiores odio totam voluptatibus! Quos commodi saepe reiciendis ex rerum voluptatem perspiciatis, eum exercitationem, laudantium nisi ipsam velit doloremque esse? A, maiores?
        Molestiae, numquam! Assumenda, voluptates? Ducimus dolor ullam, velit sit expedita, soluta repellat eveniet ratione repellendus, dolore quod libero dignissimos. Minima vel culpa, obcaecati fugiat officia quibusdam veritatis ratione praesentium ad.
        Voluptatum nisi sint nulla ipsa pariatur voluptates architecto beatae nostrum quibusdam alias illo, corporis illum. Voluptates repellat harum laudantium neque fuga, quasi suscipit, eos, nisi ab perspiciatis illum. Nobis, aperiam.
        Ducimus cumque accusantium eum laboriosam atque a vel nisi vitae. Esse illum fuga dolores, eos similique, omnis illo veniam veritatis rerum doloremque aliquid neque voluptas et reiciendis perferendis impedit suscipit.
        Laboriosam architecto, provident nemo voluptatum, quidem quod deserunt quam odio necessitatibus minus quos soluta illum vitae beatae, ad sint possimus nulla molestias accusamus exercitationem enim debitis. Aperiam autem unde obcaecati.
        Soluta voluptates exercitationem assumenda, consectetur similique, non quaerat mollitia optio saepe explicabo nisi quidem modi. Non, nesciunt nostrum placeat a provident distinctio id consequuntur ad. Pariatur aliquam error dignissimos corrupti?
        Numquam, veniam harum in quas ducimus autem perspiciatis quidem? Aperiam magni nostrum excepturi facere distinctio minus aliquid, expedita pariatur? Vero voluptate, officiis rerum neque reiciendis sint harum voluptas obcaecati fugit!
        Eaque, eligendi, repudiandae totam dignissimos vero iusto hic iure, non libero soluta odio necessitatibus maxime numquam illo dolorem assumenda fugit quos. Repellat vitae velit laudantium. Magnam tempore expedita dolores consequuntur.
        Veritatis deleniti iusto vero excepturi incidunt, deserunt quos quibusdam beatae dolores dolorem itaque aspernatur, iure maxime atque doloremque voluptate ipsum! Nemo voluptates corrupti voluptatum itaque, consequuntur fugiat a voluptatem? Beatae!
        Aut voluptas, soluta in atque rerum, ducimus eveniet perferendis reiciendis voluptatibus commodi, modi magnam. Dolorum aut eveniet possimus, provident sequi culpa placeat odit corrupti sed neque excepturi. Consectetur, iste in?
        Doloremque, ipsum hic. Numquam sapiente quidem ut repudiandae quas, autem, ipsum in distinctio laudantium non accusamus harum quisquam dolorum officiis! Amet aspernatur voluptatibus dolore similique enim saepe earum excepturi autem.
        Ex aspernatur magni tempora quae laudantium, repudiandae consequatur quo. Repellendus id nam optio veniam repudiandae doloremque similique culpa eum debitis tenetur, aspernatur, blanditiis reiciendis sequi in delectus a! Amet, illo!
        Blanditiis culpa pariatur saepe nemo, sit architecto vitae recusandae magni, fuga labore quidem adipisci? Perferendis ratione iure asperiores molestias soluta optio tenetur omnis deleniti quam commodi! Atque a ex animi!
        Voluptates vitae, assumenda nisi velit odit magni dolorum nam commodi expedita alias voluptatem minus! Totam dolorum, et error nostrum earum dignissimos veritatis rerum, accusamus eveniet fuga cumque? Dolorum, molestias eius!
        Debitis voluptas vitae alias error. Sed quaerat, sapiente unde ratione atque aspernatur expedita perspiciatis esse recusandae est odio nam porro rerum accusamus laudantium. Quos ducimus recusandae eum fugiat sint nisi?
        Corrupti laborum nemo et. Illo qui voluptatem explicabo temporibus nisi. Minima obcaecati id, asperiores commodi aut labore beatae quasi quae deleniti error praesentium? Id dolorem ullam quos adipisci. Ducimus, doloribus!
        Numquam ipsa consequuntur, vitae maxime quam nostrum optio esse. Pariatur totam porro consequuntur odit vero, obcaecati libero alias, nostrum beatae tenetur repudiandae error dolor voluptas nulla! Sit molestiae dolorum corrupti?
        Inventore nobis quae vel in possimus minus recusandae aperiam. Ab quia maiores ipsa, sint expedita consectetur, corporis est aspernatur nam, iure vero nihil! Labore officia modi iure, quos et quia!
        A quisquam voluptate illo totam molestias laudantium, atque veritatis quidem quam vero asperiores sint eum unde facere nihil minus veniam, provident est beatae quasi sapiente repellat tenetur, architecto rerum. Explicabo?
        At, obcaecati tenetur rerum laudantium aliquid porro velit, labore, reprehenderit illo quidem unde. Maiores nobis voluptatem fugiat itaque, possimus voluptatibus iusto ducimus ullam numquam quia reiciendis eius enim asperiores deserunt.
        Sed in dicta vero. Quae praesentium esse numquam eius odio molestias excepturi quasi vel beatae quidem cum quibusdam voluptatem neque doloremque maxime quo commodi expedita, blanditiis aliquid est consequatur qui.
        Accusamus fuga harum fugit vel omnis qui, sapiente eligendi sed molestias rem! Enim aliquam, at ad assumenda a rem. Sequi, sapiente. Nulla accusamus deserunt voluptas itaque sapiente eligendi illo fugiat.
        Voluptas, maxime quos molestiae optio mollitia qui repellendus tenetur, expedita pariatur animi sunt cupiditate officia voluptatibus ipsum! Cumque ut unde, doloribus excepturi labore et architecto sit non nostrum nisi ducimus.
        Odit quidem velit molestias harum hic quod facilis. Voluptatum reprehenderit illo aspernatur laboriosam neque sapiente iure asperiores architecto fugiat, velit laudantium sunt itaque atque veritatis possimus, nostrum modi facilis expedita!
        Quasi, labore expedita qui libero voluptas quisquam deserunt architecto eius esse aliquid dolorem, aliquam, sit saepe vero unde eos tempora soluta beatae tenetur magni hic explicabo! Corporis excepturi impedit labore.
        Aut nisi praesentium facilis repellat cupiditate perferendis deleniti reprehenderit mollitia enim animi illo doloribus, nostrum necessitatibus laudantium sed accusamus quia cumque eveniet. Reprehenderit aspernatur quis sapiente, explicabo repudiandae maxime iste.
        Vero repellendus numquam accusamus velit nobis? Quis eum est voluptas cupiditate id eius quasi quos ullam cumque eveniet ab ipsa ducimus, ratione, natus nostrum autem voluptate, maiores similique animi. Debitis!
        Assumenda porro expedita ad iste tempore quo fugit similique deleniti distinctio! Cum hic fugiat animi eius, explicabo deleniti, aliquid quia ea, iusto iure maiores accusantium facere doloremque asperiores similique cupiditate.
        Minima, eaque officiis quas iusto impedit eius magni consequatur nihil qui dolores repellat ex odio non, laboriosam dignissimos cupiditate quisquam iste. Eos tenetur velit temporibus pariatur autem eaque dolor nostrum.
        Quia dolorum libero nisi eveniet, delectus soluta ab dignissimos temporibus quibusdam vitae omnis repellat dolor reprehenderit et placeat, distinctio odio sed accusamus. Praesentium optio ut sapiente a, explicabo unde nulla.
        Repudiandae quibusdam commodi laudantium aut porro repellendus suscipit, praesentium nesciunt accusamus, ea atque officia cupiditate, odit quam. Provident fuga, ratione, vero temporibus quisquam dignissimos facilis sint architecto nesciunt iure vel.
        Nostrum fugit atque blanditiis mollitia laudantium consectetur ipsam non aliquid odit amet quaerat hic totam sint est laboriosam, incidunt esse facere, quasi nihil dolorem. Blanditiis magnam itaque doloremque reprehenderit obcaecati?
        Molestias deserunt ut, nihil, sint vel ex qui excepturi officia quo aliquam eaque laborum asperiores consectetur nulla impedit praesentium eius quod voluptatum maxime neque saepe adipisci, perspiciatis quibusdam amet. Officiis?
        Consequuntur laborum quisquam, at fuga recusandae eveniet culpa dolor tempora fugiat nihil autem eligendi dolorum aperiam officiis porro, error, fugit dolorem dignissimos. Id maiores nobis corporis eos adipisci sapiente dolor!
        Ut voluptatibus molestias totam quod aut placeat doloremque cupiditate. Eos quas distinctio ratione magni? Deleniti ducimus repellat maiores repudiandae facere porro? Possimus animi culpa quis voluptatibus dolorum, quibusdam saepe nesciunt!
        Velit aut atque soluta eaque dolore libero cumque quo eius ullam eveniet rerum assumenda quod sed, blanditiis enim doloribus sapiente error labore nihil, provident unde, saepe ducimus similique! Error, dolorem.
        Tempora incidunt architecto fugiat dolorum eum id nesciunt iste porro odit. A explicabo aliquid magni quidem architecto atque recusandae necessitatibus ipsam iure possimus dicta obcaecati, pariatur blanditiis quia exercitationem dolores.
        Veritatis cupiditate rem animi eaque aperiam a maiores nemo incidunt, doloremque id magnam adipisci doloribus rerum molestias quas suscipit. Quia fugiat architecto vitae aliquam officiis asperiores dolorum, earum dignissimos odit.
        Repudiandae ducimus excepturi fugit enim officia ullam consectetur, culpa, rem eveniet voluptate in distinctio quaerat modi et quasi, quam consequatur molestias quo omnis natus eius! Libero esse dolores doloribus! Nobis!
        Quaerat vitae quos recusandae consequuntur fuga, assumenda ullam ea non laboriosam, voluptate vero iure dolorum doloribus sequi obcaecati hic in esse ab et deleniti culpa tenetur? Quae voluptatem beatae dolores!
        Blanditiis expedita similique quos cumque eius possimus repellat dolorum quaerat. Voluptatem quae cumque quos totam quo, quam, beatae eligendi temporibus sit neque fugit obcaecati repellendus cupiditate velit delectus iste eveniet?
        Qui laborum recusandae fuga unde iste ad inventore alias totam rerum cumque molestias aperiam officiis nesciunt nihil, accusantium hic accusamus, tempora praesentium sed omnis ut dolore? Culpa ipsam reprehenderit cum.
        Quia nemo perspiciatis excepturi error voluptatum quaerat, aut consequuntur ex nihil, unde tenetur nam provident voluptates facilis, deleniti sint numquam rem ab eum sit sequi. Sed minus facere delectus quisquam?
        Minus, laudantium molestias. Dicta adipisci ipsum, vel enim, amet nam harum quisquam fuga consequatur non voluptates rerum obcaecati fugit odit ab corrupti. Quis, et voluptates fuga unde accusantium vel at.
        Animi, voluptates. Sapiente, nulla. Quis quaerat quod beatae dolorum sed? Deleniti delectus libero, aspernatur dolorem nostrum quidem suscipit iste totam odit inventore temporibus aperiam sit blanditiis deserunt, saepe voluptates labore.
        Natus labore illum nesciunt quasi cum facilis, earum fuga vitae, praesentium fugiat ullam. Esse saepe impedit quis, harum tempora obcaecati itaque suscipit sapiente laudantium doloremque necessitatibus cumque aspernatur velit vel?
        Soluta omnis, consectetur sunt mollitia quos debitis natus quae? Cumque mollitia assumenda a deserunt qui perspiciatis, est doloremque quis asperiores, repudiandae blanditiis id iure ab fugiat non nostrum nulla odit?
        Quas animi facere veritatis, sunt rem necessitatibus minima repudiandae aperiam iste temporibus beatae quo iusto culpa expedita unde adipisci natus molestiae veniam deserunt obcaecati? Blanditiis esse earum ab maiores dolore?
        Consequatur doloribus quidem ullam natus! Pariatur ad id optio sapiente non sed ipsam, maxime doloribus impedit libero, ut perferendis et, incidunt quae tempora quos eligendi omnis eum! Explicabo, accusantium cum?
        Inventore quibusdam maxime explicabo! Possimus sapiente ab accusantium voluptatum distinctio magni quos aliquid, qui totam, optio aliquam quidem adipisci quae iusto corrupti commodi ratione cupiditate recusandae alias molestiae quod! Alias.
        Odio aliquam necessitatibus obcaecati maiores reprehenderit pariatur nihil architecto. Laborum nisi, nesciunt molestiae ad voluptate soluta harum! Sequi et voluptates, inventore harum dolore est repudiandae doloremque magni vel nisi sunt?
        Laborum saepe doloribus hic cupiditate praesentium minima doloremque! Eius ducimus aut dolores. Quasi neque animi vero quaerat illo nesciunt perspiciatis vel ipsum excepturi? Modi hic quas dolorum, dolores magnam architecto.
        Magnam numquam eveniet qui quia perspiciatis nemo, ipsum tenetur, consequuntur aliquid ipsa et similique accusamus non maiores soluta doloremque dolores illum nesciunt ut eaque sapiente libero excepturi. Inventore, facere modi!
        Eveniet at fuga voluptate debitis sapiente impedit beatae aliquam. Dicta accusantium distinctio enim id perferendis praesentium atque magnam minima, beatae quos harum repudiandae corporis assumenda doloribus. Nam expedita accusantium pariatur.
      </h2>

    </div>
  )
}

export default Home